### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by GkvJeep** [katemonster33/CDJPScanMaster#1]
For the CCD bus, I recommend that you use the CAN driver(transceiver), for example PCA82C250. Since they are the same on the physical level. "Dominant" bits is 0.

**Comment by katemonster33** [comment]
This is an interesting suggestion, I'd never thought to use a Can transceiver. Have you been able to drive CCD using this? And without collisions? My main concern is not causing bus collisions, since that'll turn dash lights on. 

For the circuit that I have so far, I'm actually using some schematics I found that should work. They based it off J1708, but for the RX, they read the raw bus state, which, I think, is how they check for collisions.

**Comment by GkvJeep** [comment]
I saw your circuit, I did not like it.
I've been using the CAN driver for a long time, no problem.
Sent and immediately checked in the RX register.

**Comment by katemonster33** [comment]
I'm sure you didn't, I've never designed a circuit before, I'm learning as I go. I'm open to any suggestions to simplify the circuit. I'll replace what I have with the PCA82C250.

**Comment by GkvJeep** [comment]
http://s018.radikal.ru/i523/1704/2a/2cad8c373a54.png

**Comment by katemonster33** [comment]
Posting a picture of the board design isn't much help, I'd like to see the schematic, even if it's just a picture. Do you need to change resistors to drive CAN? After all the same pins (3&11) are used for CCD and CAN.

**Comment by laszlodaniel** [comment]
Although both protocols (CCD/CAN) have a common ancestor I would still use the CDP68HC68S1 chip or the Philips 4651148 variant (whichever available) because they support bus-idle and active byte detection by hardware. If you use a simpler CAN-transceiver you have to implement these by software.

**Comment by katemonster33** [comment]
I have dedicated CCD chips, the reason I don't want to use them is that they're getting harder and harder to source. Reliability is also a concern, I bought 5 of the CDP68HC68S1 off AliExpress and got 2 DOA. I'm trying to design a circuit using only components that are readily available, and if I need to bit bang it that's fine.

**Comment by GkvJeep** [comment]
Schematic added to the repository.

**Comment by katemonster33** [comment]
Thank you, that helps. Looks like you connect the chip directly to pin 3 and 11 of the OBD-II connector? Am I seeing that right?

**Comment by GkvJeep** [comment]
Yes. adding a 120 Om resistor. Pay attention to VT4, it also carries a function ISO9141.

**Comment by GkvJeep** [comment]
my old projects.
from 2001
SBEC
http://jeep.avtograd.ru/cherokee/injection/mopar/sbec/drbpc.htm
Renix
http://jeep.avtograd.ru/cherokee/faq/renix/ecu.htm

**Comment by GkvJeep** [comment]
Bear in mind that since 1996 SCI is not inverted.

**Comment by katemonster33** [comment]
Yeah I've never implemented SCI on an inverted system. I've only dealt with my 1998 ZJ and my 2003 TJ which both use non-inverted.

The only thing that I don't understand is how I'm going to isolate the ISO9141 circuit from the SCI circuit. The same pin is used for 9141 and SCI, but needs to be pulled up to 12v for 9141. I think 12V may damage the SCI circuit.

**Comment by GkvJeep** [comment]
Let's go through the email to avoid clogging up here.

**Comment by GkvJeep** [comment]
https://www.youtube.com/watch?v=ShhUJfx-1MQ
